services:
  worker:
    build: .
    command: ["python", "-m", "src.worker"]
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    restart: unless-stopped

  web:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    depends_on:
      - worker
    restart: unless-stopped
