version: '3.8'

services:
  worker:
    build: .
    container_name: linkedinagent-worker
    command: ["python", "-m", "src.worker"]
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    restart: unless-stopped

  web:
    build: .
    container_name: linkedinagent-web
    command: gunicorn -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:5000 src.main:app
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    depends_on:
      - worker
    restart: unless-stopped
