name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Check Python syntax
      run: |
        python -m py_compile app.py
        python -m py_compile config.py
        python -m py_compile database.py
        python -m py_compile linkedin_api.py
        python -m py_compile content_generator.py
        python -m py_compile news_fetcher.py
        python -m py_compile scheduler.py
    
    - name: Test database initialization
      run: |
        python -c "from database import init_db; init_db()"
      env:
        DATABASE_PATH: test.db
        GEMINI_API_KEY: test_key
        LINKEDIN_CLIENT_ID: test_id
        LINKEDIN_CLIENT_SECRET: test_secret
        LINKEDIN_REDIRECT_URI: http://localhost:5000/callback
    
    - name: Test imports
      run: |
        python -c "import config, database, linkedin_api, content_generator, news_fetcher, scheduler, app"
      env:
        DATABASE_PATH: test.db
        GEMINI_API_KEY: test_key
        LINKEDIN_CLIENT_ID: test_id
        LINKEDIN_CLIENT_SECRET: test_secret
        LINKEDIN_REDIRECT_URI: http://localhost:5000/callback

  docker:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Docker image
      run: docker build -t linkedin-bot .
